name: Create Release Zip

# Controls when the workflow will run
on:
  # Triggers when a new release is published.
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ashleyfae/action-build-release-zip@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
